*-- (c) Microsoft Corporation 1995

*-- STRINGS.H
*-- Include this file where needed for localization
*-- purposes

*-- Messagebox Titles
#DEFINE ERRORTITLE_LOC      "已发生错误"

*-- Toolbar names
#DEFINE TB_FORMDESIGNER_LOC  "表单设计器"
#DEFINE TB_STANDARD_LOC      "常用"
#DEFINE TB_LAYOUT_LOC        "布局"
#DEFINE TB_QUERY_LOC		 "查询设计器"
#DEFINE TB_VIEWDESIGNER_LOC  "视图设计器"
#DEFINE TB_COLORPALETTE_LOC  "调色板"
#DEFINE TB_FORMCONTROLS_LOC  "表单控件"
#DEFINE TB_DATADESIGNER_LOC  "数据库设计器"
#DEFINE TB_REPODESIGNER_LOC  "报表设计器"
#DEFINE TB_REPOCONTROLS_LOC  "报表控件"
#DEFINE TB_PRINTPREVIEW_LOC  "报表预览"
#DEFINE WIN_COMMAND_LOC		 "命令"			&& Command Window


*-- Messagebox Messages
#DEFINE FILENOTEXIST_LOC	"文件不存在: "
#DEFINE BADPASSWORD_LOC		"口令无效。(请参阅提示文本框)"
#DEFINE BADNAME_LOC			"未找到名称。"
#DEFINE BADUPDATE_LOC		"无法更新 - 正在恢复原始数据。"
#DEFINE SAVECHANGES_LOC		"是否要先保存更改？"
#DEFINE ASKDELETE_LOC		"是否希望删除该信息？"
#DEFINE TAGNOTFOUND_LOC		"未找到索引标识。"
#DEFINE REPORTNOTFOUND_LOC	"未找到报表文件。"
#DEFINE PRINTERNOTREADY_LOC	"打印机没有准备好。"
#DEFINE NORECSMATCHED_LOC	"没有与条件匹配的记录。"
#DEFINE DELETEREC_LOC		"是否确定要删除记录？"
#DEFINE DELETEWARN_LOC      "删除警告"
#DEFINE NOTHINGTOPRINT_LOC  "没有打印任何内容。"
#DEFINE PASSWORDEMPTY_LOC	"新的口令不能为空。"
#DEFINE PSWDNOTCNFRM_LOC    "无法确认新的口令。请再试一次。"
#DEFINE NOPSWDENTERED_LOC	"您尚未输入旧口令。是否继续？"
#DEFINE FILESAVEDAS_LOC		"文件另存为"
#DEFINE VALIDATING_LOC      "正在验证 ..."
#DEFINE PRINTING_LOC        "正在打印 ..."
#DEFINE METHOD_LOC          "方法程序:"
#DEFINE LINENUM_LOC			"行:"
#DEFINE CUSTNOORD_LOC		"客户没有次序。"
#DEFINE SELCUSTFIRST_LOC    "必须先选择一个客户。"
#DEFINE NOEMPLOYEES_LOC		"文件中没有雇员。"

*-- Other strings
#DEFINE SELECTBUTTON_LOC    "选择"
#DEFINE COPYRIGHT_LOC		"版权所有 1996 Microsoft Corporation"
#DEFINE RIGHTSRSRVD_LOC		"保留所有权利"
#DEFINE ABOUT_LOC			"关于"
#DEFINE VERSIONLABEL_LOC    "版本"
