* _TABLE2.H

***********************************
* Constants for classes
#DEFINE MB_QUESTIONYESNO	36
#DEFINE MB_ISYES			6

***********************************
* strings for _dialogbutton classes

#DEFINE ERR_NOVCXLIB_LOC 	"未找到 VCX 库！"
#DEFINE ERR_NOCLASS_LOC		"未找到类！"

***********************************
* strings for _navmenu classes

#DEFINE C_DELREC_LOC	"是否希望删除该记录？"

#DEFINE MENU_TOP_LOC	"第一个(\<T)"
#DEFINE MENU_BOTTOM_LOC	"最后一个(\<B)"
#DEFINE MENU_NEXT_LOC	"下一个(\<N)"
#DEFINE MENU_PREV_LOC	"上一个(\<P)"
#DEFINE MENU_RECORD_LOC	"记录号 #(\<R)..."
#DEFINE MENU_GOTO_LOC	"定位记录(\<G)"
#DEFINE MENU_ADD_LOC	"添加记录(\<A)"
#DEFINE MENU_DELETE_LOC	"删除记录(\<D)"
#DEFINE MENU_SORT_LOC	"排序记录..."
#DEFINE MENU_FILTER_LOC	"筛选记录(\<F)..."
#DEFINE MENU_FILTER2_LOC	"高级筛选(\<V)..."
#DEFINE ERR_UNIQUEKEY_LOC  "违反键值唯一性规则，发生错误。"
#DEFINE ERR_UNIQUEKEY2_LOC  "是否需要恢复所作的更改？"

***********************************
* strings for _sortdialog classes

#DEFINE C_NONE_LOC	"记录号 #"
#DEFINE ERR_NOTAGS_LOC	"该表中没有可排序的记录。"
#DEFINE C_NONE_LOC	"记录号 #"

