*- FOREIGN.H
*-
*- Header file for Foreign.PRG
*-
*- (c) Microsoft Corporation 1995

#DEFINE E_OPEN_LOC		"打开此文件时发生错误 @1 :"
#DEFINE E_COPY_LOC		"产生错误 @1 当试图复制目录到 "
#DEFINE E_CREATE_LOC	"创建时产生错误 @1  "
#DEFINE E_NAMEPROB_LOC	"由于文件名冲突，目录文件已重命令为"
#DEFINE E_NOFIND_LOC	"找不到移植文件 @1。"

#DEFINE C_CAT2FPC_LOC	"正在更改目录结构..."
#DEFINE C_CONFIRM1_LOC	"您在 FoxPro 中修改 &wzsString 以前必须先将其转换。原来的 @1 不会改动。是否继续转换？"
#DEFINE C_SAVETO_LOC	"将 @1 保存为:"

#DEFINE C_DBASEEOF		CHR(26)		&& code DBase use to mark EOF in .QBE file